services:
  api:
    build: .
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Servicios
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      # Agregamos las configuraciones SSL
      - SERVER_SSL_KEY_STORE=/app/cert.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=123456
      - SERVER_SSL_KEY_STORE_TYPE=PKCS12
    volumes:
      - ./src/main/resources/cert.p12:/app/cert.p12
    depends_on:
      - db
  
  db:
    image: postgres:latest
    ports:
      - "5433:5432"  # Mantenemos tu puerto modificado
    environment:
      - POSTGRES_DB=Servicios
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: